<a href="https://colab.research.google.com/github/johnlaraji1608-collab/Multinomial_Naive_Bayes./blob/main/Multinomial_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import math
from collections import defaultdict
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,ConfusionMatrixDisplay
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('/content/train (1).csv')

In [3]:
data

                                                    sms  label
0     Go until jurong point, crazy.. Available only ...      0
1                       Ok lar... Joking wif u oni...\n      0
2     Free entry in 2 a wkly comp to win FA Cup fina...      1
3     U dun say so early hor... U c already then say...      0
4     Nah I don't think he goes to usf, he lives aro...      0
...                                                 ...    ...
5569  This is the 2nd time we have tried 2 contact u...      1
5570             Will ü b going to esplanade fr home?\n      0
5571  Pity, * was in mood for that. So...any other s...      0
5572  The guy did some bitching but I acted like i'd...      0
5573                       Rofl. Its true to its name\n      0

[5574 rows x 2 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5574 entries, 0 to 5573
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sms     5574 non-null   object
 1   label   5574 non-null   int64
dtypes: int64(1), object(1)
memory usage: 87.2+ KB

In [5]:
data.duplicated().sum()

np.int64(403)

In [6]:
data=data.drop_duplicates()
data.duplicated().sum()

np.int64(0)

In [7]:
data.isnull().sum()

sms      0
label    0
dtype: int64

In [8]:
(data['sms']==0).sum()
data['label'].value_counts()

label
0    4518
1     653
Name: count, dtype: int64

In [9]:
x=data['sms']
y=data['label']
X=x.copy()
Y=y.copy()

In [10]:
vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(data['sms'])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [12]:
y_predict=model.predict(x_test)
y_predict

array([0, 1, 0, ..., 0, 0, 0])

In [13]:
print('Evaluation for Built In model:')
print('\nAccuracy:',accuracy_score(y_test,y_predict)*100,'%')
print('\nClassification Report\n',classification_report(y_test,y_predict))

Evaluation for Built In model:

Accuracy: 96.32850241545894 %

Classification Report
               precision    recall  f1-score   support

           0       0.96      1.00      0.98       898
           1       1.00      0.72      0.84       137

    accuracy                           0.96      1035
   macro avg       0.98      0.86      0.91      1035
weighted avg       0.96      0.96      0.96      1035